cs412/urls.py
from django.contrib import admin
from django.urls import path, include 
from django.conf.urls.static import static 
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hw/', include('hw.urls')),                    # Class Example
    path('quotes/', include('quotes.urls')),            # Assignment 3
    path('restaurant/', include('restaurant.urls')),    # Assignment 4
    path('blog/', include('blog.urls')),                # Class Example
    path('mini_fb/', include('mini_fb.urls')),          # Assignment 5
    path('marathon_analytics/', include('marathon_analytics.urls')), 
    path('voter_analytics/', include('voter_analytics.urls')), 
] 

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hw/urls.py
# file: hw/urls.py
from django.urls import path
from django.conf import settings
from . import views

# URL Configuration specific to the hw app 
urlpatterns = [ 
    # path(r'', views.home, name="home"), 
    path(r'', views.home, name="home"),
    path(r'about', views.about, name="about"),
] 

mini_fb/urls.py
# Anya Liu ; anyaliu@bu.edu
# This is the urls.py file for the mini_fb app.
# It maps URLs to the views in the mini_fb app.

from django.urls import path
from .views import * # our view class definition 
from django.contrib.auth import views as auth_views

urlpatterns = [
    # map the URL (empty string) to the view
    path('', ShowAllProfilesView.as_view(), name='show_all_profiles'), 
    path('show_all_profiles', ShowAllProfilesView.as_view(), name='show_all_profiles'), 
    path('profile/<int:pk>', ShowProfilePageView.as_view(), name='show_profile'), # show one profile
    # create
    path('profile/create_profile', CreateProfileView.as_view(), name='create_profile'), 
    path('profile/create_status', CreateStatusMessageView.as_view(), name='create_status'), 
    # update
    path('profile/update', UpdateProfileView.as_view(), name="update_profile"), 
    path('status/<int:pk>/update', UpdateStatusMessageView.as_view(), name="update_status"),
    # delete
    path('status/<int:pk>/delete', DeleteStatusMessageView.as_view(), name="delete_status"),
    # friend
    path('profile/add_friend/<int:other_pk>', AddFriendView.as_view(), name="add_friend"),
    path('profile/friend_suggestions', ShowFriendSuggestionsView.as_view(), name="friend_suggestions"),
    # newsfeed
    path('profile/news_feed', ShowNewsFeedView.as_view(), name="news_feed"),
    # authentication views
    path('login/', auth_views.LoginView.as_view(template_name='mini_fb/login.html'), name='login'), ## NEW
	path('logout/', auth_views.LogoutView.as_view(template_name='mini_fb/logged_out.html'), name='logout'), ## NEW
    # path('register/', RegistrationView.as_view(), name='register'),
]

mini_fb/models.py
# Anya Liu ; anyaliu@bu.edu
# This is the model for the mini_fb app.
# It defines the data structure for the mini Facebook application.

from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

# Create your models here.
class Profile(models.Model):
    '''Encapsulate the idea of Profile which has attributes of individual Facebook users.'''
    # data attributes of a Profile:
    first_name = models.TextField(blank=False)
    last_name = models.TextField(blank=False)
    city = models.TextField(blank=False)
    email_address = models.TextField(blank=False)
    image_url = models.URLField(blank=True) 
    user = models.ForeignKey(User, on_delete=models.CASCADE) 
    
    def __str__(self):
        '''Return a string representation of this Profile object.'''
        return f'{self.first_name} {self.last_name}'
    
    def get_absolute_url(self):
        '''Return the URL to display one instance of this model.'''
        return reverse('show_profile', kwargs={'pk': self.pk})
    
    # Status Message
    def get_status_messages(self):
        '''Return all of the status messages about this profile.'''
        messages = StatusMessage.objects.filter(profile=self)
        return messages
    
    # Friends
    def get_friends(self): 
        '''Return a list of Profile objects that are friends with this profile.'''
        friends1 = Profile.objects.filter(pk__in=Friend.objects.filter(profile1=self).values_list("profile2", flat=True))
        friends2 = Profile.objects.filter(pk__in=Friend.objects.filter(profile2=self).values_list("profile1", flat=True))
        return friends1.union(friends2)
    
    def add_friend(self, other): 
        '''Create a Friend connection between this profile and another profile.'''
        if self == other:
            return  # Prevent self-friending
        # Check if a Friend relationship already exists
        existing_friendship1 = Friend.objects.filter(profile1=self, profile2=other).exists()
        existing_friendship2 = Friend.objects.filter(profile1=other, profile2=self).exists()
        if not (existing_friendship1 or existing_friendship2):
            Friend.objects.create(profile1=self, profile2=other)
    
    def get_friend_suggestions(self):
        '''Return a list of Profile objects that are not already friends with this profile.'''
        existing_friends = self.get_friends()
        friends = Profile.objects.exclude(pk=self.pk).exclude(pk__in=existing_friends.values_list("pk", flat=True))
        return friends
    
    def get_news_feed(self): 
        '''Return a list of StatusMessage objects from this profile and all friends, ordered by timestamp (most recent first).'''
        friends = self.get_friends()  # Get all friends (QuerySet)
        # Get the primary keys of self and all friends
        all_profile_pks = list(friends.values_list("pk", flat=True)) + [self.pk]
        # Filter status messages using profile__in
        return StatusMessage.objects.filter(profile__pk__in=all_profile_pks).order_by('-timestamp')

class StatusMessage(models.Model):
    '''Encapsulate the idea of a Status Message on a Profile.'''
	# data attributes of a Status Message:
    profile = models.ForeignKey("Profile", on_delete=models.CASCADE) # foreign key because it refers to a different kind of model
    message = models.TextField(blank=False) # the text of the status message
    timestamp = models.DateTimeField(auto_now=True) # the time at which this status message was created/saved
    
    def __str__(self):
        '''Return a string representation of this StatusMessage object.'''
        return f'{self.message}'
    
    def get_images(self): 
        '''Return all of the images associated with this status message.'''
        images = StatusImage.objects.filter(status_message=self)
        return images

class Image(models.Model): 
    '''Encapsulate the idea of an Image file.'''
    # foreign key to indicate the relationship to the Profile of the user who uploaded this Image
    profile = models.ForeignKey("Profile", on_delete=models.CASCADE) 
    image_file = models.ImageField(blank=False) # an actual image
    timestamp = models.DateTimeField(auto_now=True) # the time at which the image was uploaded
    caption = models.TextField(blank=True) # optional: a caption that describes what's in the image

    def __str__(self):
        '''Return a string representation of this Image object.'''
        return f'Image uploaded by {self.profile.first_name} {self.profile.last_name} at {self.timestamp}'

class StatusImage(models.Model):
    '''Encapsulate the relationship between a StatusMessage and an Image.'''
    status_message = models.ForeignKey("StatusMessage", on_delete=models.CASCADE) # Link to the status message
    image = models.ForeignKey("Image", on_delete=models.CASCADE) # Link to the image

    def __str__(self):
        '''Return a string representation of this StatusImage object.'''
        return f'Image associated with StatusMessage {self.status_message.id}'

class Friend(models.Model):
    '''Encapsulate the idea of Friend, an edge connecting two nodes within the social network.'''

    profile1 = models.ForeignKey("Profile", on_delete=models.CASCADE, related_name="profile1")
    profile2 = models.ForeignKey("Profile", on_delete=models.CASCADE, related_name="profile2")
    timestamp = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        '''Return a string representation of this Friend object.'''
        return f'{self.profile1.first_name} {self.profile1.last_name} and {self.profile2.first_name} {self.profile2.last_name}'

mini_fb/views.py
# Author: Anya Liu
# Email: anyaliu@bu.edu
# This is the views.py file for the mini facebook app and defines the views for the mini_fb app.

from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView, View
from django.urls import reverse
from .models import *
from .forms import *
from django.contrib.auth.mixins import LoginRequiredMixin ## NEW
from django.contrib.auth.forms import UserCreationForm ## NEW
from django.contrib.auth.models import User ## NEW
from django.contrib.auth import login # NEW

### Profile
class ShowAllProfilesView(ListView):
    '''Create a subclass of ListView to display all Facebook Profiles.'''
    model = Profile # retrieve objects of type Profile from the database
    template_name = 'mini_fb/show_all_profiles.html'
    context_object_name = 'profiles' # how to find the data in the template file

class ShowProfilePageView(DetailView):
    '''Show the details for one profile.'''
    model = Profile
    template_name = 'mini_fb/show_profile.html'
    context_object_name = 'profile'

### CREATE VIEWS
# Create Profile
class CreateProfileView(CreateView):
    '''A view to handle creation of a new Profile.
    (1) display the HTML form to user (GET)
    (2) process the form submission and store the new Profile object (POST)
    '''
    form_class = CreateProfileForm
    template_name = "mini_fb/create_profile_form.html"

    def get_context_data(self, **kwargs):
        '''Return the dictionary of context variables for use in the template.'''
        context = super().get_context_data(**kwargs)
        # add UserCreationForm to context
        context['user_creation_form'] = UserCreationForm()
        return context

    def form_valid(self, form):
        '''
        Handle the form submission to create a new Profile object.
        '''
        user_form = UserCreationForm(self.request.POST)
        
        if user_form.is_valid():
            user = user_form.save()  # Save the new user
            login(self.request, user)  # Log in the newly created user
            form.instance.user = user  # Attach user to profile instance
            return super().form_valid(form)  # Save profile and redirect
        else:
            print("UserCreationForm errors:", user_form.errors)
            # If UserCreationForm is invalid, re-render the template with errors
            return self.render_to_response(self.get_context_data(form=form, user_creation_form=user_form))

# Create Status Message
class CreateStatusMessageView(LoginRequiredMixin, CreateView):
    '''A view to create a new status message and save it to the database.'''
    form_class = CreateStatusMessageForm
    template_name = "mini_fb/create_status_form.html"

    def get_context_data(self):
        '''Return the dictionary of context variables for use in the template.'''
        # calling the superclass method
        context = super().get_context_data()
        # find/add the profile to the context data
        profile = Profile.objects.get(user=self.request.user)
        # pk = self.kwargs['pk'] # retrieve the PK from the URL pattern
        # profile = Profile.objects.get(pk=pk)

        # add this profile into the context dictionary:
        context['profile'] = profile
        return context

    def form_valid(self, form):
        '''This method handles the form submission and saves the 
        new object to the Django database.
        We need to add the foreign key (of the Profile) to the Status Message
        object before saving it to the database.
        '''
        # pk = self.kwargs['pk'] # retrieve the PK from the URL pattern
        # profile = Profile.objects.get(pk=pk)
        profile = Profile.objects.get(user=self.request.user)
        form.instance.profile = profile # attach this profile to the status message
        sm = form.save() # save the status message to database

        # Process uploaded files
        files = self.request.FILES.getlist('files') # read the file from the form
        for file in files:
            # Create and save the Image object
            image = Image(profile=profile, image_file=file)
            image.save()

            # Link Image to StatusMessage
            status_image = StatusImage(status_message=sm, image=image)
            status_image.save()

        # delegate the work to the superclass method form_valid:
        return super().form_valid(form)

    ## show how the reverse function uses the urls.py to find the URL pattern
    def get_success_url(self):
        '''Provide a URL to redirect to after creating a new Status Message.'''
        # retrieve the PK from the URL pattern
        # pk = self.kwargs['pk']
        # call reverse to generate the URL for this Article
        # return reverse('show_profile', kwargs={'pk':pk})
        profile = Profile.objects.filter(user=self.request.user).first()
        return reverse('show_profile', kwargs={'pk': profile.pk})

### UPDATE VIEWS
# Update Profile 
class UpdateProfileView(LoginRequiredMixin, UpdateView):
    '''A view to update an Article and save it to the database.'''
    model = Profile
    form_class = UpdateProfileForm
    template_name = "mini_fb/update_profile_form.html"

    def get_object(self):
        '''Retrieve the Profile object associated with the logged-in user.'''
        return Profile.objects.get(user=self.request.user)

    def form_valid(self, form):
        '''
        Handle the form submission to create a new Profile object.
        '''
        print(f'UpdateProfileView: form.cleaned_data={form.cleaned_data}')

        return super().form_valid(form)

# Update Status Message 
class UpdateStatusMessageView(LoginRequiredMixin, UpdateView):
    '''A view to update a Status message and save it to the database.'''
    model = StatusMessage
    form_class = UpdateStatusMessageForm
    template_name = "mini_fb/update_status_form.html"
    context_object_name = 'status_message'
    
    def form_valid(self, form):
        '''
        Handle the form submission to create a new StatusMessage object.
        '''
        print(f'UpdateStatusMessageView: form.cleaned_data={form.cleaned_data}')

        return super().form_valid(form)
    
    def get_success_url(self):
        '''Return a the URL to which we should be directed after the update.'''

        # get the pk for this status message
        pk = self.kwargs.get('pk')
        status_message = StatusMessage.objects.get(pk=pk)
        
        # find the profile to which this StatusMessage is related by FK
        profile = status_message.profile
        
        # reverse to show the profile page
        return reverse('show_profile', kwargs={'pk':profile.pk})

### DELETE VIEWS
# Delete Status Message
class DeleteStatusMessageView(LoginRequiredMixin, DeleteView):
    '''A view to delete a status message and remove it from the database.'''
    template_name = "mini_fb/delete_status_form.html"
    model = StatusMessage
    context_object_name = 'status_message'

    def get_success_url(self):
        '''Return a the URL to which we should be directed after the delete.'''
        pk = self.kwargs.get('pk') # get the pk for this status message
        status_message = StatusMessage.objects.get(pk=pk)
        
        # find the profile to which this StatusMessage is related by FK
        profile = status_message.profile
        
        # reverse to show the profile page
        return reverse('show_profile', kwargs={'pk':profile.pk})

### Friends
class AddFriendView(LoginRequiredMixin, View):
    '''A view to add a friend relationship between two Profiles.'''
    
    def dispatch(self, request, *args, **kwargs):
        # Get the Profile instances
        # pk = self.kwargs.get('pk')
        other_pk = self.kwargs.get('other_pk')
        # profile = Profile.objects.get(pk=pk)
        other_profile = Profile.objects.get(pk=other_pk)
        profile = Profile.objects.get(user=request.user)

        # Call add_friend method
        profile.add_friend(other_profile)

        # Redirect back to the profile page
        return redirect('show_profile', pk=profile.pk)
    
class ShowFriendSuggestionsView(LoginRequiredMixin, DetailView):
    '''Show the friend suggestions for one profile.'''
    model = Profile
    template_name = 'mini_fb/friend_suggestions.html'
    context_object_name = 'profile'

    def get_object(self):
        return Profile.objects.get(user=self.request.user)

### News Feed
class ShowNewsFeedView(LoginRequiredMixin, DetailView): 
    '''Show the news feed for one profile.'''
    model = Profile
    template_name = 'mini_fb/news_feed.html'
    context_object_name = 'profile'

    def get_object(self):
        return Profile.objects.get(user=self.request.user)

mini_fb/templates/mini_fb/base.html
<!-- templates/base.html -->
<!-- Author: Anya Liu -->
<!-- Email: anyaliu@bu.edu -->
<!-- This is the base.html for standard header/footer and navigation links on all pages -->
{% load static %}
<html>
    <head>
        <title>Mini Facebook</title>
        <link rel="stylesheet" href="{% static 'styles-mini_fb.css' %}">
    </head>
    <body>
        <header>
            <h1>Mini Facebook</h1>
            <nav>
                <ul>
                    <li><a href="{% url 'show_all_profiles' %}">Show All</a></li>
                    <li><a href="{% url 'create_profile' %}">Create Profile</a></li>
                    {% if request.user.is_authenticated %} 
                    {% with request.user.profile_set.first as user_profile %}
                        {% if user_profile %}
                            <li><a href="{% url 'show_profile' user_profile.pk %}">My Profile</a></li>
                        {% endif %}
                    {% endwith %}
                    <li>
                        <form method="post" action="{% url 'logout' %}" style="display:inline;">
                            {% csrf_token %}
                            <button type="submit" style="border:none; background:none; color:blue; cursor:pointer;">Log out</button>
                        </form>
                    </li>
                    {% else %}
                    <li><a href="{% url 'login' %}">Log in</a></li>
                    {% endif %}
                </ul>
            </nav>
            <!-- show who's logged in -->
            {% if request.user.is_authenticated %}
            <p>Logged in user: {{ request.user }}.</p>
            {% else %}
            <p>Not logged in.</p>
            {% endif %}
        </header>
    
    {% block content %}
    {% endblock %}    
  
    <footer>
        Created by Anya Liu
    </footer>
    </body>
</html>

mini_fb/templates/mini_fb/create_profile_form.html
<!-- Author: Anya Liu -->
<!-- Email: anyaliu@bu.edu -->
<!-- This is the template to display the HTML form to create a new Profile object.-->
 
{% extends 'mini_fb/base.html' %}

{% block content %}
<header>
    <h2>Create a new Profile</h2>
</header>

<!-- display the HTML form -->
<form class="site-form" action="{% url 'create_profile' %}" method="POST">
    {% csrf_token %}
    <table>
        {{user_creation_form.as_table}}
        {{form.as_table}}
        <td>
            <input type="submit" name="submit" value="Submit">
        </td>
    </table>
</form>
{% endblock %}

mini_fb/templates/mini_fb/create_status_form.html
<!-- Author: Anya Liu -->
<!-- Email: anyaliu@bu.edu -->
<!-- This is the template to display the HTML form to create a new Status message object.-->
 
{% extends 'mini_fb/base.html' %}

{% block content %}
<header>
    <h2>Add a new Status Message for {{profile}}</h2>
</header>

<form method='POST' enctype="multipart/form-data">
    {% csrf_token %}
    <table>
        {{form.as_table}}
        <tr>
            <th>Upload Image</th>
            <td>
                <input type="file" name = "files" multiple />
            </td>
        </tr>
        <tr>
            <td>
                <input type="submit" name="submit" value="Submit">
            </td>
        </tr>
    </table>
</form>
{% endblock %}

mini_fb/templates/mini_fb/delete_status_form.html
<!-- Author: Anya Liu -->
<!-- Email: anyaliu@bu.edu -->
<!-- This is the template to display the HTML form to delete a Status Message object.-->
{% extends 'mini_fb/base.html' %}

{% block content %}

<h3>Are you sure you want to delete this Status Message?</h3>
<p>
    {{status_message}}
</p>
<p>
    {% for status_image in status_message.get_images %}
    <img src='{{status_image.image.image_file.url}}' alt='Image' width="150" height=auto>
    {% endfor %}
</p>

<!-- form to submit delete request -->
<form method='POST'>
    {% csrf_token %}
    <input type='submit' value="Delete">
</form>
<!-- form to submit cancel request -->
<form action="{% url 'show_profile' status_message.profile.pk %}" method='GET' >
    {% csrf_token %}
    <input type='submit' value="Cancel">
</form>

{% endblock %}

mini_fb/templates/mini_fb/friend_suggestions.html
<!-- Author: Anya Liu -->
<!-- Email: anyaliu@bu.edu -->
<!-- This is the template that inherits from base.html to display the friend suggestions for a single Profile -->
{% extends 'mini_fb/base.html' %}

{% block content %}
<h3>
    <a href="{% url 'show_profile' profile.pk %}">Back to {{ profile.first_name }} {{ profile.last_name }}'s Page</a>
</h3>
<h2>People {{ profile.first_name }} {{ profile.last_name }} may know:</h2>

<div style="display: flex; gap: 15px; flex-wrap: wrap; align-items: center;">
    {% for friend in profile.get_friend_suggestions %}
    <div style="text-align: center;">
        <h4>
            <a href="{% url 'add_friend' friend.pk %}">Add Friend</a>
        </h4>
        {% if friend.image_url %}
            <img src="{{ friend.image_url }}" alt="{{ friend.first_name }}" style="width: 150px; height: 150px; border-radius: 50%; object-fit: cover;">
        {% else %}
            No Image.
        {% endif %}
        <p>{{ friend.first_name }} {{ friend.last_name }}</p>
    </div>
    {% empty %}
    <p>No friend suggestions.</p>
    {% endfor %}
</div>
{% endblock %}

mini_fb/templates/mini_fb/logged_out.html
<!-- Author: Anya Liu -->
<!-- Email: anyaliu@bu.edu -->
<!-- This is the template that inherits from base.html to display the logged out page -->
{% extends 'mini_fb/base.html' %}

{% block content %}
<p>You have successfully logged out!</p>
<p>You can log in again using the navigation bar. </p>
{% endblock %}

mini_fb/templates/mini_fb/login.html
<!-- Author: Anya Liu -->
<!-- Email: anyaliu@bu.edu -->
<!-- This is the template that inherits from base.html to display the login page -->
{% extends 'mini_fb/base.html' %}

{% block content %}
<!-- This basic authentication form works.
- need to set "next" to redirect to correct page.
-->

<h1>Login</h1>
<form method="post" action="{% url 'login' %}" >
    {% csrf_token %}
    {{form}}
    <input type="submit" value="Login">
    {% if request.GET.next %}
    <input type="hidden" name="next" value="{{request.GET.next}}">
    {% else %}
    <input type="hidden" name="next" value="{% url 'show_all_profiles' %}">
    {% endif %}
</form>
<hr>
<!-- Don't have an account? <a href="{% url 'register' %}">Register here</a>. -->
{% endblock %}

mini_fb/templates/mini_fb/news_feed.html
<!-- Author: Anya Liu -->
<!-- Email: anyaliu@bu.edu -->
<!-- This is the template that inherits from base.html to display the news feed for a single Profile -->
{% extends 'mini_fb/base.html' %}

{% block content %}
<h3>
    <a href="{% url 'show_profile' profile.pk %}">Back to {{ profile.first_name }} {{ profile.last_name }}'s Page</a>
</h3>
<h2>{{ profile.first_name }} {{ profile.last_name }}'s News Feed:</h2>

<!-- Display status messages about this article -->
{% for status in profile.get_news_feed %}
    <div style="border-bottom: 1px solid #ccc; padding: 15px; margin-bottom: 15px; max-width: 600px;">
        <!-- Top section: Profile picture, Name, and Timestamp -->
        <div style="display: flex; align-items: center;">
            <!-- Profile Picture -->
            {% if status.profile.image_url %}
                <img src="{{ status.profile.image_url }}" alt="Profile Picture" 
                    style="width: 50px; height: 50px; border-radius: 50%; margin-right: 10px;">
            {% endif %}

            <!-- Name and Timestamp -->
            <div>
                <p style="margin: 0; font-weight: bold;">
                    {{ status.profile.first_name }} {{ status.profile.last_name }}
                </p>
                <p style="margin: 0; color: gray; font-size: 14px;">
                    {{ status.timestamp }}
                </p>
            </div>
        </div>

        <!-- Status Message -->
        <p style="margin-top: 10px; font-size: 16px;">{{ status.message }}</p>

        <!-- Status Images -->
        {% for status_image in status.get_images %}
            <img src="{{ status_image.image.image_file.url }}" alt="Image" 
                style="width: 150; height: auto; border-radius: 8px; margin-top: 10px;">
        {% endfor %}
    </div>
{% empty %}
    <p>No status messages yet.</p>
{% endfor %}




{% endblock %}

mini_fb/templates/mini_fb/show_all_profiles.html
<!-- Author: Anya Liu -->
<!-- Email: anyaliu@bu.edu -->
<!-- This is the template that inherits from base.html to display all profiles -->
{% extends 'mini_fb/base.html' %}

{% block content %}
<header>
    <h2>Showing All Profiles</h2>
</header>

<table>
    <thead>
        <tr>
            <th>Profile Image</th>
            <th>First Name</th>
            <th>Last Name</th>
            <th>City</th>
        </tr>
    </thead>
    <tbody>
        {% for p in profiles %}
        <tr>
            <td>
                {% if p.image_url %}
                <a href="{% url 'show_profile' p.pk %}">
                    <img src="{{ p.image_url }}" alt="Profile Image" width="250" height=auto>
                </a>
                {% else %}
                    No Image
                {% endif %}
            </td>
            <td>{{ p.first_name }}</td>
            <td>{{ p.last_name }}</td>
            <td>{{ p.city }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

mini_fb/templates/mini_fb/show_profile.html
<!-- Author: Anya Liu -->
<!-- Email: anyaliu@bu.edu -->
<!-- This is the template that inherits from base.html to display a single profile in more detail -->
{% extends 'mini_fb/base.html' %}

<h1>{{profile.first_name}} </h1>

{% block content %}
<main class="grid-container">
    
    <profile class="featured">
        <h2>{{ profile.first_name }} {{ profile.last_name }}</h2>
        {% if profile.image_url %}
		<img src="{{profile.image_url}}" alt="{{profile.image_url}}">
		{% endif %}
        
        <p>City: {{ profile.city }}</p>
        <p>Email: {{ profile.email_address }}</p>
        {% if request.user.is_authenticated and request.user == profile.user %}
        <h3>
            <a href="{% url 'update_profile' %}">Update Profile</a>
        </h3>
        <h3>
            <a href="{% url 'news_feed' %}">News Feed</a>
        </h3>
        {% endif %}
    </profile>
</main>

<!-- DISPLAY FRIENDS -->
<div>
    <h2>{{ profile.first_name }} {{ profile.last_name }}'s Friends</h2>
    <div style="display: flex; gap: 15px; flex-wrap: wrap; align-items: center;">
        {% for friend in profile.get_friends %}
        <div style="text-align: center;">
            <a href="{% url 'show_profile' friend.pk %}" style="text-decoration: none; color: inherit;">
                {% if friend.image_url %}
                <img src="{{ friend.image_url }}" alt="{{ friend.first_name }}" style="width: 150px; height: 150px; border-radius: 50%; object-fit: cover;">
                {% else %}
                    No Image.
                {% endif %}
                <p>{{ friend.first_name }} {{ friend.last_name }}</p>
            </a>
        </div>
        {% empty %}
        <p>No friends yet.</p>
        {% endfor %}
    </div>
    {% if request.user.is_authenticated and request.user == profile.user %}
    <h3>
        <a href="{% url 'friend_suggestions' %}">Friend Suggestions</a>
    </h3>
    {% endif %}
</div>
<!-- DISPLAY STATUS MESSAGES -->
<div>
    <h2>{{ profile.first_name }} {{ profile.last_name }}'s Status Messages</h2>
    {% if request.user.is_authenticated and request.user == profile.user %}
    <h3>
        <a href="{% url 'create_status' %}">Create a Status Message</a>
    </h3>
    {% endif %}

    <!-- Display status messages about this article -->
    {% for status in profile.get_status_messages %}
    <article>
        <div>
            <strong>{{status.timestamp}}</strong>
            <p>
            {{status.message}}
            </p>
            {% for status_image in status.get_images %}
            <img src='{{status_image.image.image_file.url}}' alt='Image' width="150" height=auto style="border-radius: 8px">
            {% endfor %}
            <!-- link to update or delete this status message -->
            {% if request.user.is_authenticated and request.user == profile.user %}
            <p>
                <a href="{% url 'update_status' status.pk %}">Update</a>
                <a href="{% url 'delete_status' status.pk %}">Delete</a>
            </p>
            {% endif %}
        </div>
    </article>
    {% endfor %}
</div>
{% endblock %}